public enum CuisineTypes {
    // Holds the types of dishes that our app supports

    ITALIAN, INDIAN, BURGERS, SANDWHICHES, VEGETARIAN, MEAT, DRINKS, BAKERY, VEGAN, CHINESE, MEXICAN, JAPANESE,
    VIETNAMESE, THAI, KOREAN, CARRIBEAN, FRENCH, BREAKFAST, GREEK;
}
