public enum Pref {
    ITALIAN, INDIAN, BURGERS, SANDWHICHES, VEGETARIAN, MEAT, DRINKS, BAKERY, VEGAN, CHINESE, MEXICAN, JAPANESE,
    VIETNAMESE, THAI, KOREAN, CARRIBEAN, FRENCH, BREAKFAST, GREEK;
}
